pub fn io_error_as_str(e: std::io::Error) -> &'static str {
    use std::io::ErrorKind::*;

    match e.kind() {
        AddrInUse => "address in use",
        AddrNotAvailable => "address not available",
        AlreadyExists => "entity already exists",
        ArgumentListTooLong => "argument list too long",
        BrokenPipe => "broken pipe",
        ConnectionAborted => "connection aborted",
        ConnectionRefused => "connection refused",
        ConnectionReset => "connection reset",
        CrossesDevices => "cross-device link or rename",
        Deadlock => "deadlock",
        DirectoryNotEmpty => "directory not empty",
        ExecutableFileBusy => "executable file busy",
        FileTooLarge => "file too large",
        HostUnreachable => "host unreachable",
        Interrupted => "operation interrupted",
        InvalidData => "invalid data",
        InvalidFilename => "invalid filename",
        InvalidInput => "invalid input parameter",
        IsADirectory => "is a directory",
        NetworkDown => "network down",
        NetworkUnreachable => "network unreachable",
        NotADirectory => "not a directory",
        NotConnected => "not connected",
        NotFound => "entity not found",
        NotSeekable => "seek on unseekable file",
        Other => "other error",
        OutOfMemory => "out of memory",
        PermissionDenied => "permission denied",
        QuotaExceeded => "quota exceeded",
        ReadOnlyFilesystem => "read-only filesystem or storage medium",
        ResourceBusy => "resource busy",
        StaleNetworkFileHandle => "stale network file handle",
        StorageFull => "no storage space",
        TimedOut => "timed out",
        TooManyLinks => "too many links",
        UnexpectedEof => "unexpected end of file",
        Unsupported => "unsupported",
        WouldBlock => "operation would block",
        WriteZero => "write zero",
        _ => "unknown",
    }
}
